### ISSUE TITLE
pre-feedback

### ISSUE THREAD

**Issue by raupp** [mathealgou/developmentOneZero-projecttest-903563a643f6#1]
**no src/index.js**

const PORT = 8080; -> tem que vir do environment ou usar default

usar o "cors()" 
e
koa.use((ctx) => {
  ctx.set('Access-Control-Allow-Origin', '*');
  ctx.set('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  ctx.set('Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS');
});
é redundante...

**no frontend/index.js**
serverURL = 'http://127.0.0.1/8080/' -> não deve "hardcodar" o server url, e deveria ter um let ou const... está sujando o global

**Testes**
Ta faltando um monte de testes, foca neles que foi o que ficou de entregar

**Comment by mathealgou** [comment]
Eu sei que falta o teste de criação de usuário, quais outros faltam?

**Comment by mathealgou** [comment]
Problemas resolvidos. Exceto os testes, tô trabalhando nesses.
